project:
  type: book
  
book:
  title: "CryptoBook"
  author: "Nguyen Tuan Anh"
  date: "02/19/2023"
  downloads: pdf
  chapters:
    - index.qmd
    - Preface.qmd
    - part: MathBackground.qmd
      chapters:
        - Maths_Notation.qmd
        - GuideOnSource.qmd
        - Groups.qmd
    - part: Foundations.qmd
      chapters:
        - Encoding.qmd
    - part: Symmetric.qmd
      chapters:
        - ECB.qmd
        - CBC.qmd
        - OFB_CFB.qmd
        - CTR.qmd
        - AESBasic.qmd
    - part: RSA_intro.qmd
      chapters:
        - UsefulMaths.qmd
        - RSA.qmd 
        - Attacks_RSA.qmd
        - RSA_Factorization.qmd
        - RSA_Parameters.qmd
    - part: DH_intro.qmd
      chapters:
        - DiffieHellman.qmd
        - BreakingDLP.qmd
    - part: EC_intro.qmd
      chapters:
        - Elliptic_Curve.qmd
        - EC_FiniteField.qmd
        - ECC_ECDH.qmd
        - ECC_Attacks.qmd
    - part: Miscellaneous
      chapters:
        - HashFunctions.qmd   
        - Shamir.qmd
    - FinalWords.qmd
  reader-mode: true 
  page-footer:
    left: | 
      **CryptoBook for the n00b1es** was written by Nguyen Tuan Anh, under supervision of Professor Wray Buntine, CECS, VinUniversity.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  favicon: cover.png 

bibliography: references.bib

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrbook
    toc: true
    highlight-style: github
    papersize: A4
jupyter: 
  kernelspec: 
      name: "sagemath"
      language: "sagemath"
      display_name: "SageMath 9.6"

execute: 
  output: true
  freeze: true
  echo: false 
