# Introduction to Groups {#sec-MathBG}

## Introduction

Almost cryptographic systems have its foundation in algebraic groups: RSA & Diffie-Hellman rely on groups of modulo, Elliptic Curve Cryptography relies on Algebraic Group of Elliptic Curve, etc. The knowledge of algebraic group can help you a lot in the study of attacks & defenses of Cryptography. This page will show you several concepts of Group Theory before you move on.

## (Informal) Definition & Examples 

:::{.callout-note}
# Definition

A **group** $(G, \odot)$ is a set $G$, together with a law of composition $(a, b) \rightarrow a \odot b$, with $\odot$ is a binary operation that maps each pair $(a, b) \in G \times G$ to a unique element $a \odot b \in G$. Additionally, $\odot$ satisfies these following axioms: 

**For** $a, b, c \in G$: 

+ **Associativity**: 
$$
(a \odot b) \odot c = a \odot (b \odot c)
$$ 
+ **Identity**: There exists an element $e \in G$, called **identity element**, that for any element $a \in G$: 
$$
e \odot a = a \odot e = a
$$

+ **Inverse**: For every $a \in G$, there exists an **inverse element** $a^{-1} \in G$, such that: 

$$
a \odot a^{-1} = a^{-1} \odot a = e
$$  

Furthermore, if a group holds **commutativity**, that means $a \odot b = b \odot a$, we call the group is **commutative** or **abelian**. 
::: 

One very good way to describe the group operation is using **Cayley table**, which is simply iterating every possible $a, b$ for operation $\oplus$. We will use Cayley table to show (and also an example) of $(\mathbb{Z}_{5}, +)$ (additive group of integers modulo 5). 

$$
\begin{equation*}
\begin{array}{c|ccccc}
+ & 0 & 1 & 2 & 3 & 4 \\
\hline
0 & 0 & 1 & 2 & 3 & 4 \\
1 & 1 & 2 & 3 & 4 & 0 \\
2 & 2 & 3 & 4 & 0 & 1 \\
3 & 3 & 4 & 0 & 1 & 2 \\
4 & 4 & 0 & 1 & 2 & 3
\end{array}
\end{equation*}
$$

In cryptography, we mostly play with abelian group (like $\mathbb{Z}_{p}$), because of the requirement of asymmetric crypto. 

Let's us finish this section by pointing out several important propositions of group operations. As a scope of an introduction text, I will not leave the proof here. To learn more about this topic, you can visit the book [Abstract Algebra: Theory & Application](http://abstract.ups.edu/aata/groups-section-defnitions.html)'s section about group theory. 

:::{.callout-note}
# Propositions

+ The identity element $e \in G$ is unique. That means, there is only one $e \in G$ such that holds the identity axiom given above. 
+ The inverse of an element $a \in G, a^{-1}$ is also unique. 
+ $(ab)^{-1} = b^{-1}a^{-1}$. If the group is abelian, this is also equal to $a^{-1}b^{-1} = (ba)^{-1}$
+ $(a^{-1})^{-1} = a$
:::

## Order & Generator

Next, we will have a look at the concept of order and generator of a group. **Order** is simply the cardinality of the group. If the group has finite number of elements, then we call it is a finite order group. The **generator** of a group is an element in group that can 'generate' all group elements, via applying the operation of that group 1, 2, ... to the order of the group.

Let's have an example. 
Take the example of a group $\mathbb{Z}_{13}$. If we compute number $2^x$ where $0 \le x < p - 1$, we can have a set: 

$$
\{2^x\} = \{1, 2, 4, 8, 3, 6, 12, 11, 9, 5, 10, 7\}
$$

This set is $\mathbb{Z}_{13}$, which have the order is $13$ as well. However, if we take another number, for example, 5: 

$$
\{5^x\} = \{1, 5, 12, 8\}
$$

$2$ is the generator of group $G = \mathbb{Z}_{13}$, but $5$ isn't. However, it is not restricted for a group to have only one generator. An example is the group of elliptic curve, that you will see soon. 

## Subgroup 

A subgroup $H$ of a group $G$ is a subset of $G$, that satisfies below requirements:

1. The identity $e_{G}$ of $G$ must be in $H$. 
2. $h_1, h_2 \in H$, then $h1 \odot h_2 \in H$
3. If $h \in H$, then $h^{-1} \in H$.

Continue with the example in **3.3**, the group generated by $5$ in $G = (\mathbb{Z}_{13}, \times)$ can be considered as a subgroup of $G$. 

## Group Homomorphism & Isomorphism

We have a lot of algebraic group: modulo, elliptic curve's point, etc. They may look different, but sometimes a mapping can connect them together. That is Group Homomorphism & Isomorphism. 

::: {.callout-note}
# Group Homomorphism

With two group $(G, \cdot)$ and $(H, \odot)$, a **group homomorphism** $\phi: G \leftarrow H$ is a mapping such that the group operation is preserved; that is:

$$
\phi(a \cdot b) = \phi(a) \odot \phi(b)
$$

for all $a, b \in G$. The left-hand side operation exists in $G$, while the right-hand side operation exists in $H$. 

If the mapping is **bijective**, we call $\phi$ is a **group isomorphism**.
:::

In the context of CTF and crypto, we would expect to have a group isomorphism rather than homomorphism, as bijective mapping will help us to find the correct value better and faster!

### Example 

We can define a group isomorphism $\phi$ from $(\mathbb{R}, +)$ to $(\mathbb{R}^{+}, \times)$: 

$$
\phi(x + y) = e^{x+y} = e^{x}e^{y} = \phi(x) \phi(y)
$$

We can prove this mapping is bijective, by using calculus. 

